### ISSUE TITLE
Exception when multiple threads call recvEvent()

### ISSUE THREAD

**Issue by srinivas9804** [JeffersonLab/E2SAR#64]
The following exception is thrown when multiple threads call recvEvent()

`'boost::wrapexcept<boost::lock_error>'
  what():  boost unique_lock doesn't own the mutex: Operation not permitted [generic:1]`

**Comment by ibaldin** [comment]
Made the lock used for wait_for thread-local and created ahead of time in deferred state (in recvEvent() method). Tested and performance is back to normal, but now multiple threads can read  off the queue using recvEvent().
